### ISSUE TITLE
Filter by Animal in Shortcode 

### ISSUE THREAD

**Issue by spisbell** [cferdinandi/fetch#3]
Good Morning, 

I am using the Wordpress plugin on a site I am building. This site will have a seperate page for Cats and for Dogs. I was wondering if there is a way to specify in the shortcode that I want to display only one animal type vs all animals (i.e. Only dogs, only cats).

Thanks in advanced.
Scarlett Isbell

**Comment by cferdinandi** [comment]
Hi @spisbell - not via the shortcode/plugin, but you can do this with CSS.

Most WordPress themes add a class to the `body` element that's unique to that page (something like `.page-id-20`). And each pet includes an animal type class you can hook into. You can use the two of these together to hide a type of animal on a particular page.

```css
// Hide cats
.page-id-{ID} .pf-cat {
    display: none !important;
    visibility: hidden !important;
}

// Hide dogs
.page-id-{ID} .pf-dog {
    display: none !important;
    visibility: hidden !important;
}
```

If you don't want to modify the core theme, [Jetpack](https://jetpack.com/) includes an inline CSS option. I've also had good luck with the [Art Direction](https://wordpress.org/plugins/art-direction/) plugin.
