### ISSUE TITLE
Filters bunching up, no line breaks

### ISSUE THREAD

**Issue by kfajans** [cferdinandi/fetch#9]
Thank you for this plugin. It saved a ton of time for me. 

I have a Wordpress install at http://caninecommit.org/test/ and the filters on the left side have no line breaks. It's okay for most of the selections but the breeds is a jumbled mess.

**Comment by cferdinandi** [comment]
I like to provide flexibility with styling here, so I deliberately don't force breaks into layout. You can tweak this with a little CSS:

```css
.fetch-filters label {
    width: 100%;
    display: block;
}
```
